#!/bin/sh
### BEGIN INIT INFO
# Provides: weimarnetzvpn
# Required-Start: $local_fs $network $remote_fs $syslog
# Required-Stop: $local_fs $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop the central vpn and olsr services
# Description: weimarnetzvpn provides connections between our olsr nodes
#              and also starts the olsr daemon for advanced routing
### END INIT INFO
#

# fixme! add hna4 for each /30 vpn (reachable clients without running olsrd!)

func_start ()
{
	logger -p daemon.info -t vtund[$0] request for service_start from UID $UID
	
	cp /etc/vtund.conf /var/www/freifunk/vpn/vtund_config.txt
	cp /etc/olsrd.conf /var/www/freifunk/vpn/olsrd_config.txt
	cp /etc/olsrd6.conf /var/www/freifunk/vpn/olsrd6_config.txt

	func_start_vtun
	sleep 10		# waiting for some stable conn's
	func_start_olsr
}

func_stop ()
{
	logger -p daemon.info -t "vtund[$0]" "request for service_stop from UID $UID"
	killall olsrd
#	killall vtund
	killall vtund-nossl
}

func_usage ()
{
	echo "Usage: $0 start|stop|restart \$HOSTNAME"
}


func_start_olsr ()
{
	ip address del 10.63.30.249/30 dev eth0:0
	ip address add 10.63.5.1/26 dev eth0:0

	pidof olsrd >/dev/null || {
		olsrd -f /etc/olsrd6.conf -d 0 || {
			logger -p daemon.crit -t "olsrd6[$0]" "something went wrong during olsrd-start"
		}
		olsrd -f /etc/olsrd.conf -d 0 || {
			logger -p daemon.crit -t "olsrd[$0]" "something went wrong during olsrd-start"
		}
		return
	}
	logger -p daemon.info -t "olsrd[$0]" "already started"
}

func_start_vtun ()
{
	echo `date` >> /tmp/vtun_counter
#	/usr/local/sbin/vtund -f /etc/vtund.conf -s || {
#
#		logger -p daemon.crit -t "vtund[$0]" "something went wrong during vtund-start"
#	}

	/usr/local/bin/vtund-nossl -f /etc/vtund.conf -P 5063 -s || {

                logger -p daemon.crit -t "vtund[$0]" "something went wrong during vtund-start"
	}
}

[ -e  /tmp/VPNSCRIPT ] && {
	echo "lockdatei '/tmp/VPNSCRIPT' existiert! - abbruch"
	exit
}

touch /tmp/VPNSCRIPT

GLOBAL_AGE=720		# 720h = 1 Monat

case $1 in
	start)
		func_start
	;;
	stop)
		func_stop
	;;
	restart_olsr)
		func_loop_vpn_user_requests_and_output_olsr_conf >/etc/olsrd.conf
		cp /etc/olsrd.conf /var/www/freifunk/vpn/olsrd_config.txt		
		killall olsrd
		func_start_olsr
	;;
	restart)
		func_stop
		logger -p daemon.info -t vtund[$0] short_wait && sleep 10
		rm /tmp/vpnrestart
		func_start
	;;
	*)
		func_usage
	;;
esac

rm /tmp/VPNSCRIPT
